#!/usr/bin/env bash
################################################################################
# isolation/lima.bash
#
# Provider: Lima VM (macOS)
#
# Runs test commands inside a per-run Lima virtual machine derived from a
# pre-existing base instance. The base VM must exist before sourcing this file.
#
# Usage:
#   source isolation/lima.bash
#
# Prerequisites:
#   A Lima instance named "${repo_name}.base" must exist. Create it once with
#   limactl and configure it as the baseline environment for your tests.
#
# Environment (consumed on source):
#   repo_name     - used to derive the base VM name (${repo_name}.base)
#                   and per-run VM name (${repo_name}.${git_sha})
#   git_sha       - commit SHA; used to name the VM and workspace
#   git_branch    - branch name; used as a prefix in the workspace directory
#   project_root  - repository root; workspace created under $project_root/ci/
#   CI_HOME       - (optional) override workspace root
#   artifacts_dir - path to the artefacts directory; mounted into the VM
#
# Exports:
#   test_workspace - path to the temporary working directory for this run
#   test_vm        - name of the Lima VM for this run
#
# Provider interface (all exported):
#   provider_run     - create (from base) and start the VM, retrying up to 10
#                      times; generates a minimal lima YAML on the fly
#   provider_exec    - run a bash --login command inside the VM via limactl shell;
#                      writes stderr to $OUTPUT (default /dev/null)
#   provider_stop    - stop the VM; attempts force-stop on failure
#   provider_remove  - force-stop (1s) and delete the VM
#   provider_cleanup - delete VM if it exists, then delete test_workspace
#
# Notes:
#   - The generated Lima template disables containerd (system and user) since
#     it is not needed for the test environment.
#   - If the VM already exists from a previous interrupted run it is reused and
#     the matching workspace directory is located by glob.
#   - Set OUTPUT to a file path before calling provider_exec to capture stderr.
################################################################################

#
# helpers
#

_vm_exists() {
  limactl list --format json 2>/dev/null |
    grep -q "\"name\":\"${1:?"Missing argument vm_name"}\""
}

_vm_state() {
  limactl list --format json 2>/dev/null |
    grep "\"name\":\"${1:?"Missing argument vm_name"}\"" |
    grep -o '"status":"[^"]*"' |
    grep -o '[^"]*"$' |
    tr -d '"'
}

_lima_template() {
  cat <<EOF
# Generated by lima.bash for test instance: ${test_vm}
base: template:${base_vm}

mounts:
  - location: "${test_workspace}"
    mountPoint: "${test_workspace}"
    writable: true
  - location: "${artifacts_dir}"
    mountPoint: "${artifacts_dir}"
    writable: true

containerd:
  system: false
  user: false
EOF
}

#
# provider interface
#

provider_run() {
  local max_attempts=10
  readonly max_attempts
  local attempt=1

  echo ""
  echo "Starting VM '${test_vm}'..."
  echo ""

  while true; do
    if ! _vm_exists "${test_vm}"; then
      local template_file
      template_file=$(mktemp /tmp/lima.${test_vm}.XXXXXX.yaml)
      _lima_template >"${template_file}"
      limactl create \
        --name="${test_vm}" \
        --tty=false \
        "${template_file}"
      rm -f "${template_file}"
    fi

    if [[ "$(_vm_state "${test_vm}")" != "Running" ]]; then
      limactl start --tty=false "${test_vm}"
    fi

    echo "Waiting for VM to be ready..."
    if limactl shell "${test_vm}" -- true 2>/dev/null; then
      break
    fi

    if [[ "${attempt}" -ge "${max_attempts}" ]]; then
      echo "VM not ready, max attempts exceeded (${attempt}), script exiting..."
      exit 1
    else
      echo "VM not ready, retrying (${attempt})..."
      provider_stop
    fi
    attempt=$((attempt + 1))
  done
}
export -f provider_run

provider_exec() {
  local output="${OUTPUT:-"/dev/null"}"
  readonly output

  if ! limactl shell "${test_vm}" -- /usr/bin/env bash --login -c "${@}" 2>"${output}"; then
    if [[ "${output}" != "/dev/null" && -f "${output}" ]]; then
      echo "Script failed"
      cat "${output}"
      exit 1
    fi
  fi
}
export -f provider_exec

provider_stop() {
  local timeout="${1:-60}"
  readonly timeout

  if [[ "$(_vm_state "${test_vm}")" != "Stopped" ]]; then
    if ! limactl stop "${test_vm}"; then
      echo "could not stop vm '${test_vm}', attempting force stop..."
      if ! limactl stop --force "${test_vm}"; then
        echo "could not force stop vm '${test_vm}'"
        return 1
      fi
    fi
  fi
}
export -f provider_stop

provider_remove() {
  # timeout is set to 1 to force the environment to be destroyed right away
  provider_stop 1 || :
  limactl delete --force "${test_vm}"
}
export -f provider_remove

provider_cleanup() {
  set +u
  if [[ -n "${test_vm}" ]]; then
    if _vm_exists "${test_vm}"; then
      provider_stop 1 || :
      limactl delete --force "${test_vm}"
    fi
  fi
  rm -rf "${test_workspace}"
}
export -f provider_cleanup

#
# provider specific setup
#

readonly base_vm="${repo_name}.base"
if ! _vm_exists "${base_vm}"; then
  echo "Could not find base Lima VM used for testing..." >&2
  echo "Please create a base instance named '${base_vm}' and try again." >&2
  exit 1
fi

export test_vm="${repo_name}.${git_sha}"
readonly test_vm

if ! _vm_exists "${test_vm}"; then
  if [[ -n "${CI_HOME+x}" ]] && [[ -d "${CI_HOME:-}" ]]; then
    test_workspace=$(mktemp -d "${CI_HOME}/${git_branch}.${git_sha}.XXXXXX")
  else
    test_workspace=$(mktemp -d "${project_root}/ci/${git_branch}.${git_sha}.XXXXXX")
  fi
else
  if [[ -n "${CI_HOME+x}" ]] && [[ -d "${CI_HOME:-}" ]]; then
    workspaces=("${CI_HOME}/${git_branch}.${git_sha}".*)
    test_workspace="${workspaces[0]}"
  else
    workspaces=("${project_root}/ci/${git_branch}.${git_sha}".*)
    test_workspace="${workspaces[0]}"
  fi
fi
export test_workspace
readonly test_workspace
